version: '3.3'
services:
  app:
    build:
      context: .
    environment:
      - HTTP_PORT=${HTTP_PORT}
      - WEBPUSH_SUBJECT=${WEBPUSH_SUBJECT}
      - WEBPUSH_PUBLIC_KEY=${WEBPUSH_PUBLIC_KEY}
      - WEBPUSH_PRIVATE_KEY=${WEBPUSH_PRIVATE_KEY}
      - MAX_WEBHOOK_SOCKETS=${MAX_WEBHOOK_SOCKETS}
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
    command: node server.js
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: 3